module:
  hugoVersion:
    min: "0.64.0"
  mounts:
  - source: index.html
    target: layouts/index.html
  - source: partials
    target: layouts/partials/tnd-data
  - source: console
    target: layouts/partials/tnd-data